name: CI

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore src/Philiprehberger.UrlBuilder.csproj

      - name: Build
        run: dotnet build src/Philiprehberger.UrlBuilder.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test tests/Philiprehberger.UrlBuilder.Tests/Philiprehberger.UrlBuilder.Tests.csproj --configuration Release --no-restore

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "8.0.x"

      - name: Pack
        run: dotnet pack src/Philiprehberger.UrlBuilder.csproj --configuration Release -o out

      - name: Push to NuGet
        run: dotnet nuget push out/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
